name: Anurag ServeƦ

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Processing Anurag ServeƦ
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Checking Anurag ServeƦ Runners"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization Anurag ServeƦ
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Main Repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} anurag
       - name: Running Anurag ServeƦ
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd anurag
           docker build . -t anurag
           docker run anurag
       - name: Restarting Anurag ServeƦ
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> Anurag.txt
              git add Anurag.txt
              git commit -m "Anurag ServeƦ : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.SUPER_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:AnuragServeƦ
